
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
╭─\
$directory\
$git_branch\
$git_status\
$c\
$conda\
$dart\
$docker_context\
$golang\
$guix_shell\
$haskell\
$java\
$julia\
$kotlin\
$lua\
$nix_shell\
$nodejs\
$python\
$rust\
$swift\
$terraform\
$vagrant\
$zig\
$cmd_duration\
\n╰─$sudoﬦ 
"""

[directory]
style = "fg:#FFFFFF"
truncation_length = 3
truncation_symbol = ".../"
home_symbol = "󰜥 "
format = " [$path]($style) "

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Repositories" = "󰳏 "
"Desktop" = " "
"Games" = " "
"Videos" = " "
".config" = " "
".cache" = "󰃨 "
".wine" = "󰡶"
"tuldok" = ""
"kaalaman" = " "

[git_branch]
symbol = "󰘵 "
style = "fg:#FFFFFF"
format = "⏽ [$symbol $branch]($style)"

[git_status]
style = "fg:#FFFFFF"
format = "[$all_status$ahead_behind ]($style)"
conflicted = '  '
ahead = ' \[󰤇 $count\]'
behind = ' \[󱙷 $count\]'
diverged = ' 󱡷 '
up_to_date = '  '
untracked = ' 󰏑'
stashed = ' 󰋻'
modified = ' 󱩼'
staged = ' \[[󰷬 $count\]]($style fg:#ffffff)'
renamed = ' 󰑕'
deleted = ' '

[cmd_duration]
style = "fg:#ffffff"
min_time = 0
show_milliseconds = true
format = "⏽ [$duration ]($style)"

[c]
symbol = " "
format = "⏽ [$symbol$version ]($style)"
style = "fg:#ffffff"

[conda]
symbol = " "
format = "⏽ [$symbol$environment ]($style)"
style = "fg:#ffffff"

[dart]
symbol = " "
format = "⏽ [$symbol$version ]($style)"
style = "fg:#ffffff"

[docker_context]
symbol = "󰡨 "
format = "⏽ [$symbol$context ]($style)"

[golang]
symbol = " "
format = "⏽ [$symbol$version ]($style)"
style = "fg:#ffffff"

[guix_shell]
symbol = " "
format = "⏽ [$symbol ]($style)"
style = "fg:#ffffff"

[haskell]
symbol = " "
format = "⏽ [$symbol$version ]($style)"
style = "fg:#ffffff"

[java]
symbol = " "
format = "⏽ [$symbol$version ]($style)"
style = "fg:#ffffff"

[julia]
symbol = " "
format = "⏽ [$symbol$version ]($style)"
style = "fg:#ffffff"

[kotlin]
symbol = " "
format = "⏽ [$symbol$version ]($style)"
style = "fg:#ffffff"

[lua]
symbol = " "
format = "⏽ [$symbol$version ]($style)"
style = "fg:#ffffff"

[nix_shell]
symbol = " "
format = "⏽ [$symbol$state $name ]($style)"
style = "fg:#ffffff"

[nodejs]
symbol = " "
format = "⏽ [$symbol$version ]($style)"
style = "fg:#ffffff"

[python]
symbol = " "
format = "⏽ [$symbol$version ]($style)"
style = "fg:#ffffff"

[rust]
symbol = " "
format = "⏽ [$symbol$numver ]($style)"
style = "fg:#ffffff"

[swift]
symbol = " "
format = "⏽ [$symbol$version ]($style)"
style = "fg:#ffffff"

[terraform]
symbol = "󱁢 "
format = "⏽ [$symbol$version ]($style)"
style = "fg:#ffffff"

[vagrant]
symbol = "󰼁 " # Easter egg for RoR gamers
format = "⏽ [$symbol$version ]($style)"
style = "fg:#ffffff"

[zig]
symbol = " "
format = "⏽ [$symbol$version ]($style)"
style = "fg:#ffffff"

[sudo]
style = "fg:#ffffff"
symbol = "   "
disabled = false
format = "[$symbol]($style) "
